### ISSUE TITLE
str != Parse.(str).String() when color ID is in [8,16)

### ISSUE THREAD

**Issue by davidhsingyuchen** [leaanthony/go-ansi-parser#3]
## Prologue

Thank you for this fantastic library! It saves me bunch of time :) Also, I'm not an expert of ANSI escape sequences, so it's highly possible I'm missing something, and please don't hesitate to point that out, thanks!

## Issue

The issue is caused by [this block](https://github.com/leaanthony/go-ansi-parser/blob/6785cb9688d08214b4a5f4fa5d2b8761dbc50a7b/ansi.go#L77-L84). For example, when the list of parameters is `38;5;15` (i.e., Foreground Color Code: `White`), it gets converted to `45` (i.e., Background Color Code: `Magenta`). The meaning of the parameters is drew from [here](https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797).

I assume that this behavior is not wanted because parsing a string and converting the result back to a string should not change the appearance of it.

## Example

I'm referring to something like the following part in the `Processed` image:

![image](https://user-images.githubusercontent.com/17587061/171022489-b94487e0-edc6-4bda-bac1-d6ddc5ea6216.png)

### Original

![image](https://user-images.githubusercontent.com/17587061/171022370-ddf7f471-9ee2-4362-a907-c2c680c34fc3.png)

### Processed

Parse it, do nothing to it, and print it.

![image](https://user-images.githubusercontent.com/17587061/171022446-c5dc980e-ff82-4427-a3c8-28e79252c1ca.png)

## Notes

For the references, I generate the original `.ans` file by uploading [this image](https://2.blog.xuite.net/2/0/2/4/15506077/blog_424968/txt/29824743/1.jpg) to [ASCII Art Converter](https://manytools.org/hacker-tools/convert-images-to-ascii-art/).

**Comment by leaanthony** [comment]
Thanks for the very detailed bug report and I'm glad this library is useful to you! Could you possibly make a test case for this that shows it failing? It looks like it is incorrectly processing 256 colour mode as 16 colour mode for styling.

**Comment by davidhsingyuchen** [comment]
Thanks for the prompt reply!

Adding the following test case to [TestString()](https://github.com/leaanthony/go-ansi-parser/blob/6785cb9688d08214b4a5f4fa5d2b8761dbc50a7b/ansi_test.go#L458) demonstrates the issue.

```go
		{"ANSI16 Fg Bright", []*StyledText{{Label: "White", FgCol: Cols[15]}}, "\033[0;97mWhite\033[0m"},
```

After a closer look, I think that the root cause is that regarding ANSI 16 colors, we're not handling the bright ones correctly according to [wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit) (I cannot find the original source 😅). I've also updated the PR title accordingly.

A possible solution could be:

```go
		// Do we have an ID?
		switch true {
		case s.FgCol.Id < 8:
			params = append(params, fmt.Sprintf("%d", s.FgCol.Id+30))
		case s.FgCol.Id < 16:
			params = append(params, fmt.Sprintf("%d", s.FgCol.Id-8+90))
		case s.FgCol.Id < 256:
```

If my understanding is correct, we'll also need to update the [corresponding part](https://github.com/leaanthony/go-ansi-parser/blob/6785cb9688d08214b4a5f4fa5d2b8761dbc50a7b/ansi.go#L97-L98) for the background color.

I can work on the solution, but I'm not sure why bold kicks in [here](https://github.com/leaanthony/go-ansi-parser/blob/6785cb9688d08214b4a5f4fa5d2b8761dbc50a7b/ansi.go#L81-L83), so I'd like to let you know my thoughts first to align on the approach before proceeding to the actual implementation.

Cheers!

**Comment by leaanthony** [comment]
Hi 👋 I used your original scenario of white and reproduced the error. I think it's as simple as we're not tracking the colour mode properly so `38;5;1-16` will be treated as 3/4 bit colour mode. I've added some tracking and that seems to fix the original scenario. Please check the mentioned PR to see if that fixes for you.

I think we can deal with Bold in a different issue. I've used the default 256 colour map as a basis for the conversion as specified [here](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit) and 0-7 are the default colours with 8-15 being the "bright" versions. So I think perhaps there is a need to deal with the 90 range of numbers and translate back to that when in 3/4 bit mode.

EDIT: On second reading of the Wikipedia page, it looks like `90` is an alias of `1;30` etc. So we might need to support those direct bright FG and BG colours....

**Comment by davidhsingyuchen** [comment]
Tested the PR branch locally, and it works fine! Thanks a lot :) Also, tracking the original color mode indeed seems to be cleaner.

Since the original issue is resolved by #4, please feel free to close this issue after the PR is merged and a release is cut accordingly, thanks!

Regarding the bold issue, I agree that we can discuss in another issue. In my understanding, `90` does not seem to be an alias of `1;30` though. `90` is used to represent a color different from what `30` represents, and bold is represented independently from the color. In other words, `1;30` means black with bold type, while `90` means bright black (or gray) with normal type.

**Comment by leaanthony** [comment]
Thanks for testing so quickly! I've pushed a commit to support the bright colours 90-97 & 100-107. They appear to work fine. Regarding Bold, according to Wikipedia, it works like "bright" colours: 
> to get red use ESC[31m, to get bright red use ESC[1;31m

I *think* the latest commit should work as intended. I just quickly added some code I thought was right, copy and pasted some tests + multi-cursor edited them. They appear to run fine but if you have time to verify, that would be fantastic. Thanks again for raising this and doing some great investigating into how it should work. There are so many conflicting ANSI articles 😂

**Comment by leaanthony** [comment]
Added some tests for roundtripping bright colours and found a couple of bugs. Fixes pushed 👍

**Comment by davidhsingyuchen** [comment]
Pulled the latest PR branch, and at least it works for my case (i.e., the image above in the issue description). Thank you for being very responsive :)

> to get red use ESC[31m, to get bright red use ESC[1;31m

Ah I did overlook this one, thanks a lot for pointing it out!

> There are so many conflicting ANSI articles 😂

Can't agree more as I started my ANSI journey yesterday and got so confused when just trying to find a proper intro 😓

**Comment by leaanthony** [comment]
Thanks for your time on this and finding a legitimate bug. I will tag a new release today sometime 👍

**Comment by leaanthony** [comment]
https://github.com/leaanthony/go-ansi-parser/releases/tag/v1.5.0
