### ISSUE TITLE
parse doesn't match

### ISSUE THREAD

**Issue by vendelin8** [leaanthony/go-ansi-parser#7]
Hi,

Thanks for this library!
So I started to write a little cli app with https://github.com/fatih/color, and tried to add some unit tests.
Eg. writing a color in my code looks like

```
...
import (
...
	"github.com/fatih/color"
...
)
...
colFunc = color.New(color.FgWhite, color.BgGreen, color.Bold).SprintFunc()
...
colored := colFunc("something")
...
```

Then later on I write that text t the console with another library github.com/gosuri/uilive, and it looks like white on green, but that doesn't matter, really.

Here I wanted to add some unit tests, because I have different styles and texts, and if I used the same `color.New(...` code, it doesn't look as good as parsing the output and checking out that it's really the same text with white on green background, yaaay!
So I found your library, wired it in the tests, aaand it's not always working. I can't tell if it's the same issue as the previous one.

So eg. here's what I got here in plain text: `[37;42;1msomething` but then parsing it with `parsed, err := ansi.Parse(col)` gives a parsed[0].FgCol something like:

```
&ansi.Col{Id:7, Hex:"#c0c0c0", Rgb:ansi.Rgb{R:0xc0, G:0xc0, B:0xc0}, Hsl:ansi.Hsl{H:0, S:0, L:75}, Name:"Silver"}
```

and here, result foreground name "Silver" doesn't match "White" what I'm trying to find here.
Also, Red is parsed as Maroon, Yellow as Olive and Blue as Navy.

Can you please help what can I do with this?

**Comment by leaanthony** [comment]
Best thing to do is add a test showing the problem then I can take a look 🙏

**Comment by vendelin8** [comment]
Ok, I just made the following replacements, and it works fine. Thanks a lot! :)
Also I checked out how it looks like, and `BgHiRed` is really more red than `BgRed`, so it totally makes sense to call that Maroon.
`color.FgWhite` => `color.FgHiWhite`
`color.BgRed` => `color.BgHiRed`
`color.BgYellow` => `color.BgHiYellow`
`color.BgWhite` => `color.BgHiWhite`
`color.BgBlue` => `color.BgHiBlue`
